WITH DAILY_SUBMISSIONS AS (
    SELECT 
        SUBMISSION_DATE,
        HACKER_ID,
        COUNT(SUBMISSION_ID) AS SUBMISSION_COUNT
    FROM 
        SUBMISSIONS
    GROUP BY 
        SUBMISSION_DATE, HACKER_ID
),
CONTEST_DAYS AS (
    SELECT DISTINCT 
        SUBMISSION_DATE
    FROM 
        SUBMISSIONS
),
HACKERS_PER_DAY AS (
    SELECT
        SUBMISSION_DATE,
        HACKER_ID
    FROM 
        DAILY_SUBMISSIONS
),
HACKERS_UP_TO_EACH_DAY AS (
    SELECT 
        HPD.HACKER_ID,
        CD.SUBMISSION_DATE,
        COUNT(DISTINCT HPD.SUBMISSION_DATE) AS SUBMISSION_DAYS
    FROM 
        HACKERS_PER_DAY HPD
    JOIN CONTEST_DAYS CD ON HPD.SUBMISSION_DATE <= CD.SUBMISSION_DATE
    GROUP BY 
        CD.SUBMISSION_DATE, HPD.HACKER_ID
),
HACKERS_WITH_FULL_SUBMISSION_STREAK AS (
    SELECT 
        CD.SUBMISSION_DATE,
        COUNT(DISTINCT HU.HACKER_ID) AS UNIQUE_HACKERS
    FROM 
        CONTEST_DAYS CD
    LEFT JOIN HACKERS_UP_TO_EACH_DAY HU 
        ON CD.SUBMISSION_DATE = HU.SUBMISSION_DATE
    WHERE 
        HU.SUBMISSION_DAYS = (SELECT COUNT(*) FROM CONTEST_DAYS WHERE SUBMISSION_DATE <= CD.SUBMISSION_DATE)
    GROUP BY 
        CD.SUBMISSION_DATE
),
MAX_SUBMISSIONS AS (
    SELECT 
        SUBMISSION_DATE,
        HACKER_ID,
        COUNT(SUBMISSION_ID) AS MAX_SUBMISSIONS
    FROM 
        SUBMISSIONS
    GROUP BY 
        SUBMISSION_DATE, HACKER_ID
),
HACKER_WITH_MAX_SUBMISSIONS AS (
    SELECT 
        SUBMISSION_DATE,
        HACKER_ID,
        ROW_NUMBER() OVER (PARTITION BY SUBMISSION_DATE ORDER BY MAX_SUBMISSIONS DESC, HACKER_ID ASC) AS RN
    FROM 
        MAX_SUBMISSIONS
)
SELECT 
    F.SUBMISSION_DATE,
    F.UNIQUE_HACKERS,
    H.HACKER_ID,
    HK.NAME
FROM 
    HACKERS_WITH_FULL_SUBMISSION_STREAK F
JOIN 
    HACKER_WITH_MAX_SUBMISSIONS H ON F.SUBMISSION_DATE = H.SUBMISSION_DATE AND H.RN = 1
JOIN 
    HACKERS HK ON H.HACKER_ID = HK.HACKER_ID
ORDER BY 
    F.SUBMISSION_DATE;
