WITH SUBMISSION_INFO AS (
    SELECT C.CONTEST_ID, 
    C.HACKER_ID, 
    C.NAME, 
    SUM(S.TOTAL_SUBMISSIONS) TS,
    SUM(S.TOTAL_ACCEPTED_SUBMISSIONS) TAS
    FROM COLLEGES CLG 
    JOIN CONTESTS C ON CLG.CONTEST_ID = C.CONTEST_ID
    JOIN CHALLENGES CHL ON CLG.COLLEGE_ID = CHL.COLLEGE_ID
    JOIN SUBMISSION_STATS S ON CHL.CHALLENGE_ID = S.CHALLENGE_ID
    GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME),
VIEW_INFO AS (
    SELECT C.CONTEST_ID, 
    C.HACKER_ID, 
    C.NAME, 
    SUM(V.TOTAL_VIEWS) TV,
    SUM(V.TOTAL_UNIQUE_VIEWS) TUV
    FROM COLLEGES CLG 
    JOIN CONTESTS C ON CLG.CONTEST_ID = C.CONTEST_ID
    JOIN CHALLENGES CHL ON CLG.COLLEGE_ID = CHL.COLLEGE_ID
    JOIN VIEW_STATS V ON CHL.CHALLENGE_ID = V.CHALLENGE_ID
    GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME)

SELECT SUBMISSION_INFO.CONTEST_ID, 
SUBMISSION_INFO.HACKER_ID, 
SUBMISSION_INFO.NAME,
SUBMISSION_INFO.TS,
SUBMISSION_INFO.TAS,
VIEW_INFO.TV,
VIEW_INFO.TUV
FROM SUBMISSION_INFO JOIN VIEW_INFO ON SUBMISSION_INFO.CONTEST_ID = VIEW_INFO.CONTEST_ID
AND SUBMISSION_INFO.HACKER_ID = VIEW_INFO.HACKER_ID
AND SUBMISSION_INFO.NAME = VIEW_INFO.NAME
WHERE SUBMISSION_INFO.TS > 0
AND SUBMISSION_INFO.TAS > 0
AND VIEW_INFO.TV > 0
AND VIEW_INFO.TUV > 0
ORDER BY SUBMISSION_INFO.CONTEST_ID
