SELECT H.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS CHALLENGE_COUNT
FROM HACKERS H JOIN CHALLENGES C ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(C.CHALLENGE_ID) = (SELECT TOP 1 COUNT(C1.CHALLENGE_ID)
                                FROM CHALLENGES C1
                                GROUP BY C1.HACKER_ID
                                ORDER BY COUNT(C1.CHALLENGE_ID) DESC)
OR COUNT(C.CHALLENGE_ID) NOT IN (SELECT COUNT(C2.CHALLENGE_ID)
                                 FROM CHALLENGES C2 
                                 GROUP BY C2.HACKER_ID
                                 HAVING C2.HACKER_ID <> H.HACKER_ID)
ORDER BY CHALLENGE_COUNT DESC, H.HACKER_ID
