SELECT H.HACKER_ID, H.NAME, SUM(M.MAX_SCORES)
FROM (
    SELECT S.HACKER_ID, S.CHALLENGE_ID, MAX(S.SCORE) AS MAX_SCORES
    FROM SUBMISSIONS S
    GROUP BY S.HACKER_ID, S.CHALLENGE_ID) AS M
JOIN HACKERS H ON M.HACKER_ID = H.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(M.MAX_SCORES) > 0
ORDER BY SUM(M.MAX_SCORES) DESC, H.HACKER_ID ASC
