SELECT COMPANY_COUNT.COMPANY_CODE, COMPANY.FOUNDER, COMPANY_COUNT.L, COMPANY_COUNT.S, COMPANY_COUNT.M, COMPANY_COUNT.E
FROM (SELECT DISTINCT COMPANY_CODE, COUNT(DISTINCT LEAD_MANAGER_CODE) L, COUNT(DISTINCT SENIOR_MANAGER_CODE) S, COUNT(DISTINCT MANAGER_CODE) M, COUNT(DISTINCT EMPLOYEE_CODE) E FROM EMPLOYEE
GROUP BY COMPANY_CODE) AS COMPANY_COUNT
JOIN COMPANY ON COMPANY_COUNT.COMPANY_CODE = COMPANY.COMPANY_CODE
ORDER BY COMPANY_COUNT.COMPANY_CODE
