SELECT Doctor, Professor, Singer, Actor
FROM (
    SELECT ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS ROWNUMBER, 
    NAME, 
    OCCUPATION 
    FROM OCCUPATIONS) AS OCCUPATIONROW
PIVOT (MAX(NAME) 
       FOR OCCUPATION IN ([Doctor], [Professor], [Singer], [Actor])) AS PIVOTTABLE
ORDER BY ROWNUMBER
