SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS W JOIN WANDS_PROPERTY P ON W.CODE = P.CODE
WHERE W.COINS_NEEDED = (SELECT MIN(COINS_NEEDED)
                       FROM WANDS W2 JOIN WANDS_PROPERTY P2 ON W2.CODE = P2.CODE
                       WHERE P2.IS_EVIL = 0
                       AND P.AGE = P2.AGE
                       AND W.POWER = W2.POWER)
ORDER BY W.POWER DESC, P.AGE DESC
