WITH DATES AS (SELECT START_DATE, END_DATE
              FROM (
              SELECT T.START_DATE, T.END_DATE
              FROM PROJECTS T
              LEFT JOIN PROJECTS T2 ON T.END_DATE = T2.START_DATE
              WHERE T2.START_DATE IS NULL) AS T
              UNION ALL SELECT T2.START_DATE, T.END_DATE
              FROM DATES T JOIN PROJECTS T2 ON T.START_DATE = T2.END_DATE)
SELECT START_DATE, END_DATE
FROM (
SELECT MIN(START_DATE) START_DATE, END_DATE
FROM DATES
GROUP BY END_DATE) AS T
ORDER BY DATEDIFF (day, START_DATE, END_DATE) , START_DATE
