SELECT CONCAT(NAME,'(',LEFT(OCCUPATION,1),')')
FROM OCCUPATIONS
ORDER BY NAME;
SELECT CONCAT('There are a total of ',OCCP_COUNT,' ',OCCP,'s.')
FROM (SELECT COUNT(NAME) AS OCCP_COUNT, LOWER(OCCUPATION) AS OCCP
FROM OCCUPATIONS
GROUP BY OCCUPATION) AS OCCUPATION_COUNT
ORDER BY OCCP_COUNT
