WITH ORDEREDSTATION AS (
    SELECT LAT_N, 
    ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROWASC, 
    ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROWSDESC,
    COUNT(*) OVER () AS TOTALROWS
    FROM STATION)
SELECT CAST(AVG(LAT_N) AS DECIMAL(15,4)) AS MEDIAN
FROM ORDEREDSTATION
WHERE ROWASC = ROWSDESC OR ROWASC + 1 = ROWSDESC
