SELECT STATION.CITY, LEN(STATION.CITY) AS CITY_LENGTH
FROM STATION,
(SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH
FROM STATION
ORDER BY LEN(CITY), CITY) AS MINLENGTH,
(SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH
FROM STATION
ORDER BY LEN(CITY) DESC, CITY) AS MAXLENGTH
WHERE STATION.CITY = MINLENGTH.CITY
OR STATION.CITY = MAXLENGTH.CITY
